### ISSUE TITLE
Lora's

### ISSUE THREAD

**Issue by cerias** [hqnicolas/StableDiffusionROCm#1]
Have you tried to use SD 1.5 Loras? 

Currently it breaks the complete generation on my side. Default checkpoints are working and also control-net. But any lora will break the generation.

On the 1.9.x branch for the 6XXX series :)

**Comment by hqnicolas** [comment]
hello @cerias Thanks for trying SD on ROCm.
my github profile image was made this way, using SD1.5 lora on the 7800XT I have been using the loras made by [kohya](https://github.com/hqnicolas/bmaltaisKohya_ssROCm/tree/main)

My training [Config Files](https://github.com/hqnicolas/bmaltaisKohya_ssROCm/tree/main/config)

Also for SDXL Loras I use [Fooocus](https://github.com/hqnicolas/lllyasvielFooocusROCm/tree/main)
I think Fooocus is a better Lora experience.
You can make the SDXL loras with [this config](https://github.com/hqnicolas/bmaltaisKohya_ssROCm/blob/main/config/config_rocm_sdxl_512_adam8.json)
and follow [this tutorial](https://www.youtube.com/watch?v=0ab2uOi2-3A)
